import 'package:rbac_client/rbac.dart';
import '../../../core/permissions.dart';
import 'contact_item.dart';

part 'contact_repository.g.dart';

/// Abstract contract for Contact data operations.
///
/// [ContactRepositoryGuarded] is auto-generated by `build_runner` and enforces
/// the declared [Access] permissions before each call.
@GenerateRBACWrapper()
abstract class ContactRepository {
  @Access.permission(DemoPermission.contactView)
  Future<List<ContactItem>> fetchContacts();

  @Access.permission(DemoPermission.contactAdd)
  Future<void> addContact({required String name, required String phone});

  @Access.permission(DemoPermission.contactDelete)
  Future<void> deleteContact(String id);
}
